:toc:


== How to play

To start a new game type `\taboo` on chat. The bot will create a new game and wait for players to join, you need at least 4 players to be able to play. The game will start after 5 minutes.

When the game starts each players will be assigned to one of two teams randomly.

At the beginning of each turn the bot will choose a clue giver from one team and a word watcher from the opposite team, then it will send a private message with the card to be played.

The clue giver has to make their team guess the word on the card without using any of the taboo words. A word is guessed when one of the members of the team type the correct word on chat.

At the same time the word watcher must attent that the clue giver don't use any of the taboo
words, if that's the case, they could use the command `\buzz` to skip to the next card.

At the end of each turn the clue giver's team receives a point for each word guessed and the
opposite team will receive a point for each word skipped.

The game ends when each player has been the clue giver once.

== Commands

=== Game

[cols=".^1,2", width="90%"]
|===

^s| Command ^s| Description

| `\taboo \t`
| Creates a new game if there is not another game currently playing. The game will wait 5 minutes for other players to join before starting.

| `\buzz`
| Use the "`buzzer`".

| `\join \j`
| Adds you to the current game.

| `\leave \l`
| Removes you from the current game.

| `\skip \s`
| Skips the current card. Only the clue giver at the time can use this command.

| `\start`
| Forces the game to start.

| `\stop`
| Stops the game.

|===

=== Cards

[cols=".^1,2", width="90%"]
|===

^s| Command ^s| Description

| `\addcard \ac`
a| Adds a new card to the deck.

Usage:

----
\addcard <word> <taboo word 1> <taboo word 2> ...
----

| `\card \c`
a| Shows a card as it is in the database.

Usage:

----
\showcard <word>
----

| `\delcard \dc`
a| Removes a card from the deck.

Usage:

----
\delcard <word>
----

| `\replcard \rc`
a| Replaces a card from the database, if the card does not exist it is added instead.

Usage:

----
\replcard <word> <taboo word 1> <taboo word 2> ...
----

|===

=== Miscellaneous

[cols=".^1,2", width="90%"]
|===

^s| Command ^s| Description

| `\addadmin \aa`
a| *_Bot owner only_*. Adds an admin to the admin list.

Usage:

----
\addadmin @<admin>
----

| `\listadmins \la`
| *_Admins only_*. List all the administrators.

| `\listconf \lc`
| *_Admins only_*. Lists the server configuration.

| `\help`
| Shows a small description of what each command does.

| `\removeadmin \ra`
| *_Bot owner only_*. Removes and admin from admin list.

|  `\repo`
| Posts a link to the bot's git repository.

| `\setchannel \sc`
a| *_Admins only_*. Sets the channel or channel to be used by the bot. The bot will only listen to those channels.

Usage:

----
\setchannel #<channel 1> #<channel 2> ...
----

| `\setrounds \sr`
a| *_Adminds only_*. Sets the number of rounds per game (default is 1). This variable is global and will be applied to all the games.

Usage:

----
\setrounds <number of rounds>
----

| `\settime \st`
a| *_Admins only_*. Sets the timer per turn in seconds (default is 120). This variable is global and will be aplied to all the games.

Usage:

----
\settime <seconds>
----

|===

== How to run

To start the bot, the bot's token and owner's id must be passed as parameters:

----
python bot.py -t <token> -o <owner_id>
----