:toc:

= Taboo extension

== How to play

To start a new game type `\taboo new` on chat.
The bot will create a new game and wait for other players to join,
the game will start after 5 minutes or when someone types `\taboo start` on chat.
Be aware that you need at least 4 players to start a new game.

Once the game starts each players will be assigned to one of two teams randomly.
Then a _giver_ is going to be selected. The role of the _giver_ is to try to make their team
guess the word in the card without saying any of the taboo words, antonyms, synonyms, or parts of
those words. For example, if the card is the one showed on the <<card_example>>, the clue giver can
not say the words _cook_or _book_, nor any of the taboo words.

[[card_example]]
.Card example
[Source, diff]
----
+ Cookbook // <1>
--------------------
- Coucine // <2>
- Instructions
- Recipe
- Food
----
<1> Word to guess
<2> Taboo words

The members of the guessing team can guess word by typing the command `\taboo` followed by the
word they are trying to guess, for the previous card the command would look like this: `\taboo
cookbook`.

If the opposite team hears the _giver_ say a taboo word, they can skip the current card bt typing
`\taboo buzz`. Take note that this command only works when the card is on play.

On the other hand, if the _giver_ thinks that the card is to hard or unguessable they can skip
the card by using the command `\taboo skip`.

The game ends when each player has been the _giver_ at least once once.

== Commands

Note that `[aboo]` indicates that this part of the command is optional and it can be written
simply as `\t`.

=== Game

[cols=".^1,2", width="90%"]
|===

^s| Command ^s| Description

| `\t[aboo]`
a| Use it to guess a word.

Usage:

----
\t[aboo] <word>
----

| `\t[aboo] buzz`
a| Use the "`buzzer`". When used by any member of opposite team it will skip the current card on
play.

| `\t[aboo] join`
| Adds you to the current game.

| `\t[aboo] leave`
| Removes you from the current game.

| `\t[aboo] skip`
| Skips the current card. Only the _giver_ at the time can use this command.

| `\t[aboo] start`
| Forces the game to start.

| `\t[aboo] stop`
| Stops the game.

|===

=== Cards

[cols=".^1,2", width="90%"]
|===

^s| Command ^s| Description

| `\t[aboo] addcard`
a| Adds a new card to the deck. You need at least 5 words to add a new card to the database,
where the first word is the card to be guessed, and the rest are taboo words. If "`word`" has
more than one word it must be enclosed between double quotation marks, i.e. `"New york"`.

Usage:

----
\taboo addcard <word> <taboo word 1> <taboo word 2> ...
----

| `\t[aboo] card <word>`
a| Shows a card as it is in the database.

Usage:

----
\taboo card <word>
----

| `\t[aboo] delcard`
a| Removes a card from the deck.

Usage:

----
\taboo delcard <word>
----

| `\t[aboo] replcard`
a| Similar to `addcard`, replaces a card from the database, if the card does not exists it is added
to the database instead.

Usage:

----
\taboo replcard <word> <taboo word 1> <taboo word 2> ...
----

|===

=== Miscellaneous

[cols=".^1,2", width="90%"]
|===

^s| Command ^s| Description

| `\t[aboo] channel`
a| *_Admins only_*. Sets the channel or channels to be used by the bot. The bot will only listen
to these channels to play a game.

Usage:

----
\setchannel <#channel 1> <#channel 2> ...
----

| `\t[aboo] setrounds`
a| *_Adminds only_*. Sets the number of rounds per game (default is 1). This variable is global and will be applied to all the games.

Usage:

----
\t[aboo] setrounds <number of rounds>
----

| `\t[aboo] settime`
a| *_Admins only_*. Sets the timer per turn in seconds (default is 120). This variable is global and will be aplied to all the games.

Usage:

----
\t[aboo] settime <seconds>
----

|===